### ISSUE TITLE
Doesn't work with scss and bootstrap

### ISSUE THREAD

**Issue by sheerun** [cprecioso/parcel-plugin-purgecss#6]
```
$ parcel build index.html
🚨  /Users/sheerun/Source/Projects/project/theme/index.scss: Cannot find module 'parcel-bundler/src/assets/CSSAsset'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/sheerun/Source/Projects/project/theme/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/sheerun/Source/Projects/project/theme/node_modules/parcel-plugin-purgecss/asset.js:10:18)
    at Module._compile (/Users/sheerun/Source/Projects/project/theme/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

**Comment by sheerun** [comment]
Ok I solved this particular error by installing parcel-bundler instead of parcel, but still extra css is not removed from package. I import scss files in index.js as so: `import './index.scss';` in `index.html` I just import `index.js`

**Comment by cprecioso** [comment]
I wasn't using the Parcel` API correctly, and only doing this when reading CSS files.
As of `v2.0.0` it transforms all files that convert to CSS. @sheerun check if it works now!

As for the `parcel-bundler` vs. `parcel`, yes I use `parcel-bundler` because that's what they direct everyone to do from their main page. I wasn't even aware that `parcel` was valid.

**Comment by cprecioso** [comment]
Also, note that it will only run on `parcel build`!

**Comment by millette** [comment]
Can we add a note to the readme mentionning the `parcel-bunder` peer dep? I'm just starting with Parcel, so I'm not sure if it's a usual requirement or not.

**Comment by cprecioso** [comment]
Yes, I can add the note, but keep in mind that since this is a `parcel` plugin, it's only natural that you also need it.

**Comment by millette** [comment]
Yeah, I'm figuring that out. It's confusing since parcel and parcel-bundler appear to be the same thing. I've switched to using parcel-bundler now. Like you said, it's to be expected and noting so in the readme probably isn't important.
